apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-endpoint-config
  namespace: {{ .Release.Namespace }}
data:
  MYSQL_HOST: {{ .Values.configmap.mysqlEndpoint.host | quote }}
  MYSQL_PORT: {{ .Values.configmap.mysqlEndpoint.port | quote }}