apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: django
  ports:
  - protocol: TCP
    port: {{ .Values.django.service.port }}
    targetPort: {{ .Values.django.service.port }}
    nodePort: {{ .Values.django.service.nodePort }}