apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: {{ .Values.mysql.service.port }}
    targetPort: {{ .Values.mysql.service.port }}
  type: ClusterIP