apiVersion: v1
kind: Secret
metadata:
  name: email-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  EMAIL_HOST_USER: {{ .Values.email.hostUser | b64enc }}
  EMAIL_HOST_PASSWORD: {{ .Values.email.hostPassword | b64enc }}